@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Dec 11 13:58:21 +0800 2021
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim AXI4Lite_singleRW_tb_behav -key {Behavioral:sim_1:Functional:AXI4Lite_singleRW_tb} -tclbatch AXI4Lite_singleRW_tb.tcl -protoinst "protoinst_files/bd_48f7.protoinst" -protoinst "protoinst_files/AXI4Lite_singleRW_sys.protoinst" -view F:/Onedrive/VivadoPrj/AXI4LiteMaster_singleRW_useFIFO/AXI4Lite_singleRW_tb_behav.wcfg -log simulate.log"
call xsim  AXI4Lite_singleRW_tb_behav -key {Behavioral:sim_1:Functional:AXI4Lite_singleRW_tb} -tclbatch AXI4Lite_singleRW_tb.tcl -protoinst "protoinst_files/bd_48f7.protoinst" -protoinst "protoinst_files/AXI4Lite_singleRW_sys.protoinst" -view F:/Onedrive/VivadoPrj/AXI4LiteMaster_singleRW_useFIFO/AXI4Lite_singleRW_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
